bracelets = {
    male = {
        [1] = {
            label = 'Không đeo',
            cType = 'props',
            drawble = -1,
            textures = 0,
        },
        [2] = {
            label = 'Vòng sắt',
            cType = 'props',
            drawble = 0,
            textures = 0,
        },
        [3] = {
            label = 'Vòng sắt to',
            cType = 'props',
            drawble = 1,
            textures = 0,
        },
        [4] = {
            label = 'Vòng sắt to 2',
            cType = 'props',
            drawble = 2,
            textures = 0,
        },
        [5] = {
            label = 'Vòng sắt đầu lâu',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [6] = {
            label = 'Vòng sắt bảng to',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [7] = {
            label = 'Vòng sắt dây',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [8] = {
            label = 'Vòng su gai',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },
        [9] = {
            label = 'Vòng tay su',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },
        [10] = {
            label = 'Vòng tay su 1',
            cType = 'props',
            drawble = 7,
            textures = 1,
        },
        [11] = {
            label = 'Vòng tay su 2',
            cType = 'props',
            drawble = 7,
            textures = 2,
        },
        [12] = {
            label = 'Vòng tay su 3',
            cType = 'props',
            drawble = 7,
            textures = 3,
        },
        [13] = {
            label = 'Vòng phát sáng',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },
        [14] = {
            label = 'Vòng phát sáng 1',
            cType = 'props',
            drawble = 8,
            textures = 1,
        },
        [15] = {
            label = 'Vòng phát sáng 2',
            cType = 'props',
            drawble = 8,
            textures = 2,
        },
        [16] = {
            label = 'Vòng phát sáng 3',
            cType = 'props',
            drawble = 8,
            textures = 3,
        },
        [17] = {
            label = 'Vòng phát sáng 4',
            cType = 'props',
            drawble = 8,
            textures = 4,
        },
        [18] = {
            label = 'Vòng phát sáng 5',
            cType = 'props',
            drawble = 8,
            textures = 5,
        },
        [19] = {
            label = 'Vòng phát sáng 6',
            cType = 'props',
            drawble = 8,
            textures = 6,
        },
        [20] = {
            label = 'Vòng phát sáng 7',
            cType = 'props',
            drawble = 8,
            textures = 7,
        },
        [21] = {
            label = 'Vòng phát sáng 8',
            cType = 'props',
            drawble = 8,
            textures = 8,
        },
        [22] = {
            label = 'Vòng phát sáng 9',
            cType = 'props',
            drawble = 8,
            textures =9,
        },
        [23] = {
            label = 'Vòng phát sáng 10',
            cType = 'props',
            drawble = 8,
            textures = 10,
        },
        [24] = {
            label = 'Vòng phát sáng 11',
            cType = 'props',
            drawble = 8,
            textures = 11,
        },
        [25] = {
            label = 'Vòng tay 1 vòng s1',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },
        [26] = {
            label = 'Vòng tay 1 vòng s2',
            cType = 'props',
            drawble = 9,
            textures = 1,
        },
        [27] = {
            label = 'Vòng tay 1 vòng s3',
            cType = 'props',
            drawble = 9,
            textures = 2,
        },
        [28] = {
            label = 'Vòng su bảng to s1',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },
        [29] = {
            label = 'Vòng su bảng to s2',
            cType = 'props',
            drawble = 10,
            textures = 1,
        },
        [30] = {
            label = 'Vòng su bảng to s3',
            cType = 'props',
            drawble = 10,
            textures = 2,
        },
        [31] = {
            label = 'Vòng su bảng to s4',
            cType = 'props',
            drawble = 10,
            textures = 3,
        },
        [32] = {
            label = 'Vòng su bảng to s5',
            cType = 'props',
            drawble = 10,
            textures = 4,
        },
        [33] = {
            label = 'Vòng sắt tròn nhỏ s1',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },
        [34] = {
            label = 'Vòng sắt tròn nhỏ s2',
            cType = 'props',
            drawble = 11,
            textures = 1,
        },
        [35] = {
            label = 'Vòng sắt tròn nhỏ s3',
            cType = 'props',
            drawble = 11,
            textures = 2,
        },
        [36] = {
            label = 'Vòng sắt tròn nhỏ s4',
            cType = 'props',
            drawble = 11,
            textures = 3,
        },
        [37] = {
            label = 'Vòng sắt tròn nhỏ s5',
            cType = 'props',
            drawble = 11,
            textures = 4,
        },
        [38] = {
            label = 'Vòng su 1 vòng s1',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },
        [39] = {
            label = 'Vòng su 1 vòng s2',
            cType = 'props',
            drawble = 12,
            textures = 1,
        },
        [40] = {
            label = 'Vòng su 1 vòng s3',
            cType = 'props',
            drawble = 12,
            textures = 2,
        },
        [41] = {
            label = 'Vòng su 1 vòng s4',
            cType = 'props',
            drawble = 12,
            textures = 3,
        },
        [42] = {
            label = 'Vòng su 1 vòng s5',
            cType = 'props',
            drawble = 12,
            textures = 4,
        },
        [43] = {
            label = 'Vòng su 1 vòng s6',
            cType = 'props',
            drawble = 12,
            textures = 5,
        },
        [44] = {
            label = 'Vòng su 1 vòng s7',
            cType = 'props',
            drawble = 12,
            textures = 6,
        },
        [45] = {
            label = 'Vòng su 1 vòng s8',
            cType = 'props',
            drawble = 12,
            textures = 7,
        },
        [46] = {
            label = 'Vòng su 1 vòng s9',
            cType = 'props',
            drawble = 12,
            textures = 8,
        },
        [47] = {
            label = 'Vòng su 1 vòng s10',
            cType = 'props',
            drawble = 12,
            textures = 9,
        },
        [48] = {
            label = 'Vòng su 1 vòng s11',
            cType = 'props',
            drawble = 12,
            textures = 10,
        },
        [49] = {
            label = 'Vòng su 1 vòng s12',
            cType = 'props',
            drawble = 12,
            textures = 11,
        },
        [50] = {
            label = 'Vòng su 1 vòng s13',
            cType = 'props',
            drawble = 12,
            textures = 12,
        },
        [51] = {
            label = 'Vòng su 1 vòng s14',
            cType = 'props',
            drawble = 12,
            textures = 13,
        },
    },
    female = {
        [1] = {
            label = 'Không đeo',
            cType = 'props',
            drawble = -1,
            textures = 0,
        },
        [2] = {
            label = 'Vòng tay s1',
            cType = 'props',
            drawble = 0,
            textures = 0,
        },
        [3] = {
            label = 'Vòng tay s2',
            cType = 'props',
            drawble = 1,
            textures = 0,
        },
        [4] = {
            label = 'Vòng tay s3',
            cType = 'props',
            drawble = 2,
            textures = 0,
        },
        [5] = {
            label = 'Vòng tay s4',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [6] = {
            label = 'Vòng tay s5',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [7] = {
            label = 'Vòng tay s6',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [8] = {
            label = 'Vòng tay s7',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },
        [9] = {
            label = 'Vòng tay s8',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },
        [10] = {
            label = 'Vòng tay s9',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },
        [11] = {
            label = 'Vòng tay s10',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },
        [12] = {
            label = 'Vòng tay s11',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },
        [13] = {
            label = 'Vòng tay s12',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },
        [14] = {
            label = 'Vòng tay s13',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },
        [15] = {
            label = 'Vòng tay s14',
            cType = 'props',
            drawble = 13,
            textures = 0,
        },
        [16] = {
            label = 'Vòng tay s15',
            cType = 'props',
            drawble = 14,
            textures = 0,
        },
        [17] = {
            label = 'Vòng tay s16',
            cType = 'props',
            drawble = 14,
            textures = 1,
        },
        [18] = {
            label = 'Vòng tay s17',
            cType = 'props',
            drawble = 14,
            textures = 2,
        },
        [19] = {
            label = 'Vòng tay s18',
            cType = 'props',
            drawble = 14,
            textures = 3,
        },
        [20] = {
            label = 'Vòng tay s19',
            cType = 'props',
            drawble = 15,
            textures = 0,
        },
        [21] = {
            label = 'Vòng tay s20',
            cType = 'props',
            drawble = 15,
            textures = 1,
        },
        [22] = {
            label = 'Vòng tay s21',
            cType = 'props',
            drawble = 15,
            textures = 2,
        },
        [23] = {
            label = 'Vòng tay s22',
            cType = 'props',
            drawble = 15,
            textures = 3,
        },
        [24] = {
            label = 'Vòng tay s23',
            cType = 'props',
            drawble = 15,
            textures = 4,
        },
        [25] = {
            label = 'Vòng tay s24',
            cType = 'props',
            drawble = 15,
            textures = 5,
        },
        [26] = {
            label = 'Vòng tay s25',
            cType = 'props',
            drawble = 15,
            textures = 6,
        },
        [27] = {
            label = 'Vòng tay s26',
            cType = 'props',
            drawble = 15,
            textures = 7,
        },
        [28] = {
            label = 'Vòng tay s27',
            cType = 'props',
            drawble = 15,
            textures = 8,
        },
        [29] = {
            label = 'Vòng tay s28',
            cType = 'props',
            drawble = 15,
            textures = 9,
        },
        [30] = {
            label = 'Vòng tay s29',
            cType = 'props',
            drawble = 15,
            textures = 10,
        },
        [31] = {
            label = 'Vòng tay s30',
            cType = 'props',
            drawble = 15,
            textures = 11,
        },
        [32] = {
            label = 'Vòng tay s31',
            cType = 'props',
            drawble = 16,
            textures = 0,
        },
        [33] = {
            label = 'Vòng tay s32',
            cType = 'props',
            drawble = 16,
            textures = 1,
        },
        [34] = {
            label = 'Vòng tay s33',
            cType = 'props',
            drawble = 16,
            textures = 2,
        },
        [35] = {
            label = 'Vòng tay s34',
            cType = 'props',
            drawble = 17,
            textures = 0,
        },
        [36] = {
            label = 'Vòng tay s35',
            cType = 'props',
            drawble = 17,
            textures = 1,
        },
        [37] = {
            label = 'Vòng tay s36',
            cType = 'props',
            drawble = 17,
            textures = 2,
        },
        [38] = {
            label = 'Vòng tay s37',
            cType = 'props',
            drawble = 17,
            textures = 3,
        },
        [39] = {
            label = 'Vòng tay s38',
            cType = 'props',
            drawble = 17,
            textures = 4,
        },
        [40] = {
            label = 'Vòng tay s39',
            cType = 'props',
            drawble = 18,
            textures = 0,
        },
        [41] = {
            label = 'Vòng tay s40',
            cType = 'props',
            drawble = 18,
            textures = 1,
        },
        [42] = {
            label = 'Vòng tay s41',
            cType = 'props',
            drawble = 18,
            textures = 2,
        },
        [43] = {
            label = 'Vòng tay s42',
            cType = 'props',
            drawble = 18,
            textures = 3,
        },
        [44] = {
            label = 'Vòng tay s43',
            cType = 'props',
            drawble = 18,
            textures = 4,
        },
        [45] = {
            label = 'Vòng tay s44',
            cType = 'props',
            drawble = 19,
            textures = 0,
        },
        [46] = {
            label = 'Vòng tay s45',
            cType = 'props',
            drawble = 19,
            textures = 1,
        },
        [47] = {
            label = 'Vòng tay s46',
            cType = 'props',
            drawble = 19,
            textures = 2,
        },
        [48] = {
            label = 'Vòng tay s47',
            cType = 'props',
            drawble = 19,
            textures = 3,
        },
        [49] = {
            label = 'Vòng tay s48',
            cType = 'props',
            drawble = 19,
            textures = 4,
        },
        [50] = {
            label = 'Vòng tay s49',
            cType = 'props',
            drawble = 19,
            textures = 5,
        },
        [51] = {
            label = 'Vòng tay s50',
            cType = 'props',
            drawble = 19,
            textures = 6,
        },
        [52] = {
            label = 'Vòng tay s51',
            cType = 'props',
            drawble = 19,
            textures = 7,
        },
        [53] = {
            label = 'Vòng tay s52',
            cType = 'props',
            drawble = 19,
            textures = 8,
        },
        [54] = {
            label = 'Vòng tay s53',
            cType = 'props',
            drawble = 19,
            textures = 9,
        },
        [55] = {
            label = 'Vòng tay s54',
            cType = 'props',
            drawble = 19,
            textures = 10,
        },
        [56] = {
            label = 'Vòng tay s55',
            cType = 'props',
            drawble = 19,
            textures = 11,
        },
        [57] = {
            label = 'Vòng tay s56',
            cType = 'props',
            drawble = 19,
            textures = 12,
        },
        [58] = {
            label = 'Vòng tay s57',
            cType = 'props',
            drawble = 19,
            textures = 13,
        },
    }
}