ear = {
    male = {
        [1] = {
            label = 'Không đeo khuyên tai',
            cType = 'props',
            drawble = -1,
            textures = 0,
        },
        [2] = {
            label = 'Tai nghe không dây',
            cType = 'props',
            drawble = 0,
            textures = 0,
        },
        [3] = {
            label = 'Tai nghe không dây 2',
            cType = 'props',
            drawble = 1,
            textures = 0,
        },
        [4] = {
            label = 'Tai nghe không dây 3',
            cType = 'props',
            drawble = 2,
            textures = 0,
        },
        [5] = {
            label = 'Khuyên vòng vàng trái',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [6] = {
            label = 'Khuyên vòng đen trái',
            cType = 'props',
            drawble = 3,
            textures = 1,
        },
        [7] = {
            label = 'Khuyên vòng bạc trái',
            cType = 'props',
            drawble = 3,
            textures = 2,
        },
        [8] = {
            label = 'Khuyên vòng vàng phải',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [9] = {
            label = 'Khuyên vòng đen phải',
            cType = 'props',
            drawble = 4,
            textures = 1,
        },
        [10] = {
            label = 'Khuyên vòng bạc phải',
            cType = 'props',
            drawble = 4,
            textures = 2,
        },
        [11] = {
            label = 'Khuyên vòng vàng hai bên',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [12] = {
            label = 'Khuyên vòng đen hai bên',
            cType = 'props',
            drawble = 5,
            textures = 1,
        },
        [13] = {
            label = 'Khuyên vòng bạc hai bên',
            cType = 'props',
            drawble = 5,
            textures = 2,
        },
        [14] = {
            label = 'Khuyên tròn vàng trái',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },
        [15] = {
            label = 'Khuyên tròn bạc trái',
            cType = 'props',
            drawble = 6,
            textures = 1,
        },
        [16] = {
            label = 'Khuyên tròn vàng phải',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },
        [17] = {
            label = 'Khuyên tròn bạc phải',
            cType = 'props',
            drawble = 7,
            textures = 1,
        },
        [18] = {
            label = 'Khuyên tròn vàng hai bên',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },
        [19] = {
            label = 'Khuyên tròn bạc hai bên',
            cType = 'props',
            drawble = 8,
            textures = 1,
        },
        [20] = {
            label = 'Khuyên kim cương vàng trái',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },
        [21] = {
            label = 'Khuyên kim cương đen trái',
            cType = 'props',
            drawble = 9,
            textures = 1,
        },
        [22] = {
            label = 'Khuyên kim cương bạc trái',
            cType = 'props',
            drawble = 9,
            textures = 2,
        },
        [23] = {
            label = 'Khuyên kim cương vàng phải',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },
        [24] = {
            label = 'Khuyên kim cương đen phải',
            cType = 'props',
            drawble = 10,
            textures = 1,
        },
        [25] = {
            label = 'Khuyên kim cương bạc phải',
            cType = 'props',
            drawble = 10,
            textures = 2,
        },
        [26] = {
            label = 'Khuyên kim cương vàng hai bên',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },
        [27] = {
            label = 'Khuyên kim cương đen hai bên',
            cType = 'props',
            drawble = 11,
            textures = 1,
        },
        [28] = {
            label = 'Khuyên kim cương bạc hai bên',
            cType = 'props',
            drawble = 11,
            textures = 2,
        },
        [29] = {
            label = 'Khuyên ngôi sao vàng trái',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },
        [30] = {
            label = 'Khuyên ngôi sao đen trái',
            cType = 'props',
            drawble = 12,
            textures = 1,
        },
        [31] = {
            label = 'Khuyên ngôi sao bạc trái',
            cType = 'props',
            drawble = 12,
            textures = 2,
        },
        [32] = {
            label = 'Khuyên ngôi sao vàng phải',
            cType = 'props',
            drawble = 13,
            textures = 0,
        },
        [33] = {
            label = 'Khuyên ngôi sao đen phải',
            cType = 'props',
            drawble = 13,
            textures = 1,
        },
        [34] = {
            label = 'Khuyên ngôi sao bạc phải',
            cType = 'props',
            drawble = 13,
            textures = 2,
        },
        [35] = {
            label = 'Khuyên ngôi sao vàng hai bên',
            cType = 'props',
            drawble = 14,
            textures = 0,
        },
        [36] = {
            label = 'Khuyên ngôi sao đen hai bên',
            cType = 'props',
            drawble = 14,
            textures = 1,
        },
        [37] = {
            label = 'Khuyên ngôi sao bạc hai bên',
            cType = 'props',
            drawble = 14,
            textures = 2,
        },
        [38] = {
            label = 'Khuyên vòng nhỏ vàng trái',
            cType = 'props',
            drawble = 15,
            textures = 0,
        },
        [39] = {
            label = 'Khuyên vòng nhỏ đen trái',
            cType = 'props',
            drawble = 15,
            textures = 1,
        },
        [40] = {
            label = 'Khuyên vòng nhỏ bạc trái',
            cType = 'props',
            drawble = 15,
            textures = 2,
        },
        [41] = {
            label = 'Khuyên vòng nhỏ vàng phải',
            cType = 'props',
            drawble = 16,
            textures = 0,
        },
        [42] = {
            label = 'Khuyên vòng nhỏ đen phải',
            cType = 'props',
            drawble = 16,
            textures = 1,
        },
        [43] = {
            label = 'Khuyên vòng nhỏ bạc phải',
            cType = 'props',
            drawble = 16,
            textures = 2,
        },
        [44] = {
            label = 'Khuyên vòng nhỏ vàng hai bên',
            cType = 'props',
            drawble = 17,
            textures = 0,
        },
        [45] = {
            label = 'Khuyên vòng nhỏ đen hai bên',
            cType = 'props',
            drawble = 17,
            textures = 1,
        },
        [46] = {
            label = 'Khuyên vòng nhỏ bạc hai bên',
            cType = 'props',
            drawble = 17,
            textures = 2,
        },
        [47] = {
            label = 'Khuyên tứ giác vàng sáng trái',
            cType = 'props',
            drawble = 18,
            textures = 0,
        },
        [48] = {
            label = 'Khuyên tứ giác vàng ánh trái',
            cType = 'props',
            drawble = 18,
            textures = 1,
        },
        [49] = {
            label = 'Khuyên tứ giác đen trái',
            cType = 'props',
            drawble = 18,
            textures = 2,
        },
        [50] = {
            label = 'Khuyên tứ giác bạc trái',
            cType = 'props',
            drawble = 18,
            textures = 3,
        },
        [51] = {
            label = 'Khuyên tứ giác vàng xám trái',
            cType = 'props',
            drawble = 18,
            textures = 4,
        },
        [52] = {
            label = 'Khuyên tứ giác vàng sáng phải',
            cType = 'props',
            drawble = 19,
            textures = 0,
        },
        [53] = {
            label = 'Khuyên tứ giác vàng ánh phải',
            cType = 'props',
            drawble = 19,
            textures = 1,
        },
        [54] = {
            label = 'Khuyên tứ giác đen phải',
            cType = 'props',
            drawble = 19,
            textures = 2,
        },
        [55] = {
            label = 'Khuyên tứ giác bạc phải',
            cType = 'props',
            drawble = 19,
            textures = 3,
        },
        [56] = {
            label = 'Khuyên tứ giác vàng xám phải',
            cType = 'props',
            drawble = 19,
            textures = 4,
        },
        [57] = {
            label = 'Khuyên tứ giác vàng sáng hai bên',
            cType = 'props',
            drawble = 20,
            textures = 0,
        },
        [58] = {
            label = 'Khuyên tứ giác vàng ánh hai bên',
            cType = 'props',
            drawble = 20,
            textures = 1,
        },
        [59] = {
            label = 'Khuyên tứ giác đen hai bên',
            cType = 'props',
            drawble = 20,
            textures = 2,
        },
        [60] = {
            label = 'Khuyên tứ giác bạc hai bên',
            cType = 'props',
            drawble = 20,
            textures = 3,
        },
        [61] = {
            label = 'Khuyên tứ giác vàng xám hai bên',
            cType = 'props',
            drawble = 20,
            textures = 4,
        },
        [62] = {
            label = 'Khuyên chữ S vàng trái',
            cType = 'props',
            drawble = 21,
            textures = 0,
        },
        [63] = {
            label = 'Khuyên chữ S bạc trái',
            cType = 'props',
            drawble = 21,
            textures = 1,
        },
        [64] = {
            label = 'Khuyên chữ S vàng phải',
            cType = 'props',
            drawble = 22,
            textures = 0,
        },
        [65] = {
            label = 'Khuyên chữ S bạc phải',
            cType = 'props',
            drawble = 22,
            textures = 1,
        },
        [66] = {
            label = 'Khuyên chữ S vàng hai bên',
            cType = 'props',
            drawble = 23,
            textures = 0,
        },
        [67] = {
            label = 'Khuyên chữ S bạc hai bên',
            cType = 'props',
            drawble = 23,
            textures = 1,
        },
        [68] = {
            label = 'Khuyên đầu lâu bạc trái',
            cType = 'props',
            drawble = 24,
            textures = 0,
        },
        [69] = {
            label = 'Khuyên đầu lâu vàng trái',
            cType = 'props',
            drawble = 24,
            textures = 1,
        },
        [70] = {
            label = 'Khuyên đầu lâu đen trái',
            cType = 'props',
            drawble = 24,
            textures = 2,
        },
        [71] = {
            label = 'Khuyên đầu lâu trắng trái',
            cType = 'props',
            drawble = 24,
            textures = 3,
        },
        [72] = {
            label = 'Khuyên đầu lâu bạc phải',
            cType = 'props',
            drawble = 25,
            textures = 0,
        },
        [73] = {
            label = 'Khuyên đầu lâu vàng phải',
            cType = 'props',
            drawble = 25,
            textures = 1,
        },
        [74] = {
            label = 'Khuyên đầu lâu đen phải',
            cType = 'props',
            drawble = 25,
            textures = 2,
        },
        [75] = {
            label = 'Khuyên đầu lâu trắng phải',
            cType = 'props',
            drawble = 25,
            textures = 3,
        },
        [76] = {
            label = 'Khuyên đầu lâu bạc hai bên',
            cType = 'props',
            drawble = 26,
            textures = 0,
        },
        [77] = {
            label = 'Khuyên đầu lâu vàng hai bên',
            cType = 'props',
            drawble = 26,
            textures = 1,
        },
        [78] = {
            label = 'Khuyên đầu lâu đen hai bên',
            cType = 'props',
            drawble = 26,
            textures = 2,
        },
        [79] = {
            label = 'Khuyên đầu lâu trắng hai bên',
            cType = 'props',
            drawble = 26,
            textures = 3,
        },
        [80] = {
            label = 'Khuyển tai đinh bên trái',
            cType = 'props',
            drawble = 27,
            textures = 0,
        },
        [81] = {
            label = 'Khuyển tai đinh bên trái',
            cType = 'props',
            drawble = 27,
            textures = 1,
        },
        [82] = {
            label = 'Khuyển tai đinh bên phải',
            cType = 'props',
            drawble = 28,
            textures = 0,
        },
        [83] = {
            label = 'Khuyển tai đinh bên phải',
            cType = 'props',
            drawble = 28,
            textures = 1,
        },
        [85] = {
            label = 'Khuyên tai đinh hai bên',
            cType = 'props',
            drawble = 29,
            textures = 0,
        },
        [86] = {
            label = 'Khuyên tai đinh hai bên',
            cType = 'props',
            drawble = 29,
            textures = 1,
        },
        [87] = {
            label = 'Khuyên tai vuông bên trái',
            cType = 'props',
            drawble = 30,
            textures = 0,
        },        
        [88] = {
            label = 'Khuyên tai vuông bên trái',
            cType = 'props',
            drawble = 30,
            textures = 1,
        },        
        [89] = {
            label = 'Khuyên tai vuông bên trái',
            cType = 'props',
            drawble = 30,
            textures = 2,
        },
        [90] = {
            label = 'Khuyên tai vuông bên phải',
            cType = 'props',
            drawble = 31,
            textures = 0,
        },        
        [91] = {
            label = 'Khuyên tai vuông bên phải',
            cType = 'props',
            drawble = 31,
            textures = 1,
        },        
        [92] = {
            label = 'Khuyên tai vuông bên phải',
            cType = 'props',
            drawble = 31,
            textures = 2,
        },
        [93] = {
            label = 'Khuyên tai vuông hai bên',
            cType = 'props',
            drawble = 32,
            textures = 0,
        },        
        [94] = {
            label = 'Khuyên tai vuông hai bên',
            cType = 'props',
            drawble = 32,
            textures = 1,
        },        
        [95] = {
            label = 'Khuyên tai vuông hai bên',
            cType = 'props',
            drawble = 32,
            textures = 2,
        },
        [96] = {
            label = 'Khuyên tai vuông cỡ lớn bên trái',
            cType = 'props',
            drawble = 34,
            textures = 0,
        },        
        [97] = {
            label = 'Khuyên tai vuông cỡ lớn bên trái',
            cType = 'props',
            drawble = 34,
            textures = 1,
        },
        [98] = {
            label = 'Khuyên tai vuông cỡ lớn bên phải',
            cType = 'props',
            drawble = 35,
            textures = 0,
        },        
        [99] = {
            label = 'Khuyên tai vuông cỡ lớn bên phải',
            cType = 'props',
            drawble = 35,
            textures = 1,
        },
        [100] = {
            label = 'Khuyên tai vuông cỡ lớn hai bên',
            cType = 'props',
            drawble = 36,
            textures = 0,
        },        
        [101] = {
            label = 'Khuyên tai vuông cỡ lớn hai bên',
            cType = 'props',
            drawble = 36,
            textures = 1,
        },
        [102] = {
            label = 'Khuyên tai cái chuông',
            cType = 'props',
            drawble = 37,
            textures = 0,
        },        
        [103] = {
            label = 'Khuyên tai cái chuông',
            cType = 'props',
            drawble = 37,
            textures = 1,
        },
        [104] = {
            label = 'Khuyên tai thẻ bài',
            cType = 'props',
            drawble = 38,
            textures = 0,
        },        
        [105] = {
            label = 'Khuyên tai thẻ bài',
            cType = 'props',
            drawble = 38,
            textures = 1,
        },        
        [106] = {
            label = 'Khuyên tai thẻ bài',
            cType = 'props',
            drawble = 38,
            textures = 2,
        },        
        [107] = {
            label = 'Khuyên tai thẻ bài',
            cType = 'props',
            drawble = 38,
            textures = 3,
        },
        [108] = {
            label = 'Khuyên tai xúc xắc',
            cType = 'props',
            drawble = 39,
            textures = 0,
        },        
        [109] = {
            label = 'Khuyên tai xúc xắc',
            cType = 'props',
            drawble = 39,
            textures = 1,
        },        
        [110] = {
            label = 'Khuyên tai xúc xắc',
            cType = 'props',
            drawble = 39,
            textures = 2,
        },        
        [111] = {
            label = 'Khuyên tai xúc xắc',
            cType = 'props',
            drawble = 39,
            textures = 3,
        },
        [112] = {
            label = 'Khuyên tai chip',
            cType = 'props',
            drawble = 40,
            textures = 0,
        },        
        [113] = {
            label = 'Khuyên tai chip',
            cType = 'props',
            drawble = 40,
            textures = 1,
        },        
        [114] = {
            label = 'Khuyên tai chip',
            cType = 'props',
            drawble = 40,
            textures = 2,
        },        
        [115] = {
            label = 'Khuyên tai chip',
            cType = 'props',
            drawble = 40,
            textures = 3,
        },
        [116] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 0,
        },        
        [117] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 1,
        },        
        [118] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 2,
        },        
        [119] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 3,
        },        
        [120] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 4,
        },        
        [121] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 5,
        },        
        [122] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 6,
        },        
        [123] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 7,
        },        
        [124] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 8,
        },        
        [125] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 9,
        },        
        [126] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 10,
        },        
        [127] = {
            label = 'Tai nghe điện thoại không dây',
            cType = 'props',
            drawble = 41,
            textures = 11,
        },
    },
    female = {    
        [1] = {
            label = 'Không đeo khuyên tai',
            cType = 'props',
            drawble = -1,
            textures = 0,
        },
        [2] = {
            label = 'Tai nghe không dây',
            cType = 'props',
            drawble = 0,
            textures = 0,
        },
        [3] = {
            label = 'Tai nghe không dây v2',
            cType = 'props',
            drawble = 1,
            textures = 0,
        },
        [4] = {
            label = 'Tai nghe không dây v3',
            cType = 'props',
            drawble = 2,
            textures = 0,
        },
        [5] = {
            label = 'Khuyên tai giọt nước',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [6] = {
            label = 'Khuyên tai giọt nước v2',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [7] = {
            label = 'Khuyên tai mặt tròn nhỏ',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [8] = {
            label = 'Khuyên tai hình thoi 0',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },        
        [9] = {
            label = 'Khuyên tai hình thoi 1',
            cType = 'props',
            drawble = 6,
            textures = 1,
        },        
        [10] = {
            label = 'Khuyên tai hình thoi 2',
            cType = 'props',
            drawble = 6,
            textures = 2,
        },
        [11] = {
            label = 'Khuyên tai thanh dài 0',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },        
        [12] = {
            label = 'Khuyên tai thanh dài 1',
            cType = 'props',
            drawble = 7,
            textures = 1,
        },        
        [13] = {
            label = 'Khuyên tai thanh dài 2',
            cType = 'props',
            drawble = 7,
            textures = 2,
        },
        [14] = {
            label = 'Khuyên tai thanh dài v2 0',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },        
        [15] = {
            label = 'Khuyên tai thanh dài v2 1',
            cType = 'props',
            drawble = 8,
            textures = 1,
        },        
        [16] = {
            label = 'Khuyên tai thanh dài v2 2',
            cType = 'props',
            drawble = 8,
            textures = 2,
        },
        [18] = {
            label = 'Khuyên tai thanh dài v3 0',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },        
        [19] = {
            label = 'Khuyên tai thanh dài v3 1',
            cType = 'props',
            drawble = 9,
            textures = 1,
        },        
        [20] = {
            label = 'Khuyên tai thanh dài v3 2',
            cType = 'props',
            drawble = 9,
            textures = 2,
        },
        [21] = {
            label = 'Khuyên tai thanh dài v4 0',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },        
        [22] = {
            label = 'Khuyên tai thanh dài v4 1',
            cType = 'props',
            drawble = 10,
            textures = 1,
        },        
        [23] = {
            label = 'Khuyên tai thanh dài v4 2',
            cType = 'props',
            drawble = 10,
            textures = 2,
        },
        [24] = {
            label = 'Khuyên tai thanh dài v5 0',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },        
        [25] = {
            label = 'Khuyên tai thanh dài v5 1',
            cType = 'props',
            drawble = 11,
            textures = 1,
        },        
        [26] = {
            label = 'Khuyên tai thanh dài v5 2',
            cType = 'props',
            drawble = 11,
            textures = 2,
        }, 
        [27] = {
            label = 'Khuyên tai tròn nhỏ 0',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },        
        [28] = {
            label = 'Khuyên tai tròn nhỏ 1',
            cType = 'props',
            drawble = 12,
            textures = 1,
        },        
        [29] = {
            label = 'Khuyên tai tròn nhỏ 2',
            cType = 'props',
            drawble = 12,
            textures = 2,
        },
        [30] = {
            label = 'Khuyên tai vòng tròn 0',
            cType = 'props',
            drawble = 13,
            textures = 0,
        },
        [31] = {
            label = 'Khuyên tai vòng tròn v2 0',
            cType = 'props',
            drawble = 14,
            textures = 0,
        },
        [32] = {
            label = 'Khuyên tai vòng tròn v3 0',
            cType = 'props',
            drawble = 15,
            textures = 0,
        },
        [33] = {
            label = 'Khuyên tai vòng tròn v4 0',
            cType = 'props',
            drawble = 16,
            textures = 0,
        },
        [34] = {
            label = 'Khuyên tai cái chuông 0',
            cType = 'props',
            drawble = 18,
            textures = 0,
        },        
        [35] = {
            label = 'Khuyên tai cái chuông 1',
            cType = 'props',
            drawble = 18,
            textures = 1,
        },
        [37] = {
            label = 'Khuyên tai thẻ bài 0',
            cType = 'props',
            drawble = 19,
            textures = 0,
        },        
        [38] = {
            label = 'Khuyên tai thẻ bài 1',
            cType = 'props',
            drawble = 19,
            textures = 1,
        },        
        [39] = {
            label = 'Khuyên tai thẻ bài 2',
            cType = 'props',
            drawble = 19,
            textures = 2,
        },        
        [40] = {
            label = 'Khuyên tai thẻ bài 3',
            cType = 'props',
            drawble = 19,
            textures = 3,
        }, 
        [41] = {
            label = 'Khuyên tai xúc xắc 0',
            cType = 'props',
            drawble = 20,
            textures = 0,
        },        
        [42] = {
            label = 'Khuyên tai xúc xắc 1',
            cType = 'props',
            drawble = 20,
            textures = 1,
        },        
        [43] = {
            label = 'Khuyên tai xúc xắc 2',
            cType = 'props',
            drawble = 20,
            textures = 2,
        },        
        [44] = {
            label = 'Khuyên tai xúc xắc 3',
            cType = 'props',
            drawble = 20,
            textures = 3,
        },   
        [45] = {
            label = 'Khuyên tai chip 0',
            cType = 'props',
            drawble = 21,
            textures = 0,
        },        
        [46] = {
            label = 'Khuyên tai chip 1',
            cType = 'props',
            drawble = 21,
            textures = 1,
        },        
        [47] = {
            label = 'Khuyên tai chip 2',
            cType = 'props',
            drawble = 21,
            textures = 2,
        },        
        [48] = {
            label = 'Khuyên tai chip 3',
            cType = 'props',
            drawble = 21,
            textures = 3,
        },
        [49] = {
            label = 'Tai nghe không dây v4 0',
            cType = 'props',
            drawble = 22,
            textures = 0,
        },        
        [50] = {
            label = 'Tai nghe không dây v4 1',
            cType = 'props',
            drawble = 22,
            textures = 1,
        },        
        [51] = {
            label = 'Tai nghe không dây v4 2',
            cType = 'props',
            drawble = 22,
            textures = 2,
        },        
        [52] = {
            label = 'Tai nghe không dây v4 3',
            cType = 'props',
            drawble = 22,
            textures = 3,
        },        
        [53] = {
            label = 'Tai nghe không dây v4 4',
            cType = 'props',
            drawble = 22,
            textures = 4,
        },        
        [54] = {
            label = 'Tai nghe không dây v4 5',
            cType = 'props',
            drawble = 22,
            textures = 5,
        },        
        [55] = {
            label = 'Tai nghe không dây v4 6',
            cType = 'props',
            drawble = 22,
            textures = 6,
        },        
        [56] = {
            label = 'Tai nghe không dây v4 7',
            cType = 'props',
            drawble = 22,
            textures = 7,
        },        
        [57] = {
            label = 'Tai nghe không dây v4 8',
            cType = 'props',
            drawble = 22,
            textures = 8,
        },        
        [58] = {
            label = 'Tai nghe không dây v4 9',
            cType = 'props',
            drawble = 22,
            textures = 9,
        },        
        [59] = {
            label = 'Tai nghe không dây v4 10',
            cType = 'props',
            drawble = 22,
            textures = 10,
        },        
        [60] = {
            label = 'Tai nghe không dây v4 11',
            cType = 'props',
            drawble = 22,
            textures = 11,
        },  
    },                                                                                                                                                   
}