watch = {
    male = {
        [1] = {
            cType = 'props',
            drawble = 0,
            textures = {
                [0] = {
                    label = 'Đồng hồ sterm',
                    price = 500,
                    type = 'money', -- coin
                    image = 'watch_5',
                },
                [1] = {
                    label = 'Đồng hồ điện tử quai đen',
                    price = 500,
                    type = 'money', -- coin
                    image = 'watch_5',
                },
            },
        },
        [2] = {
            label = 'Đồng hồ điện tử quai đen',
            cType = 'props',
            drawble = 1,
            textures = 1,
        },
        [3] = {
            label = 'Đồng hồ diosol đen',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [4] = {
            label = 'Đồng hồ diosol đỏ',
            cType = 'props',
            drawble = 3,
            textures = 1,
        },
        [5] = {
            label = 'Đồng hồ diosol trắng',
            cType = 'props',
            drawble = 3,
            textures = 2,
        },
        [6] = {
            label = 'Đồng hồ diosol vàng',
            cType = 'props',
            drawble = 3,
            textures = 3,
        },
        [7] = {
            label = 'Đồng hồ diosol xanh dương',
            cType = 'props',
            drawble = 3,
            textures = 4,
        },
        [8] = {
            label = 'Đồng hồ cegerny vàng',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [9] = {
            label = 'Đồng hồ cegerny trắng',
            cType = 'props',
            drawble = 4,
            textures = 1,
        },
        [10] = {
            label = 'Đồng hồ cegerny đen',
            cType = 'props',
            drawble = 4,
            textures = 2,
        },
        [11] = {
            label = 'Đồng hồ cegerny trắng mặt vàng',
            cType = 'props',
            drawble = 4,
            textures = 3,
        },
        [12] = {
            label = 'Đồng hồ điện tử quai trắng',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [13] = {
            label = 'Đồng hồ điện tử quai nâu',
            cType = 'props',
            drawble = 5,
            textures = 1,
        },
        [14] = {
            label = 'Đồng hồ điện tử quai da',
            cType = 'props',
            drawble = 5,
            textures = 2,
        },
        [15] = {
            label = 'Đồng hồ điện tử quai vàng',
            cType = 'props',
            drawble = 5,
            textures = 3,
        },
        [16] = {
            label = 'Đồng hồ victa Speed màu đồng',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },
        [17] = {
            label = 'Đồng hồ victa Speed màu bạc',
            cType = 'props',
            drawble = 6,
            textures = 1,
        },
        [18] = {
            label = 'Đồng hồ victa Speed màu đen',
            cType = 'props',
            drawble = 6,
            textures = 2,
        },
        [19] = {
            label = 'Đồng hồ lục giác màu bạc',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },
        [20] = {
            label = 'Đồng hồ lục giác màu đen',
            cType = 'props',
            drawble = 7,
            textures = 1,
        },
        [21] = {
            label = 'Đồng hồ lục giác màu vàng',
            cType = 'props',
            drawble = 7,
            textures = 2,
        },
        [22] = {
            label = 'Đồng hồ cơ màu đồng quai da',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },
        [23] = {
            label = 'Đồng hồ cơ màu đen',
            cType = 'props',
            drawble = 8,
            textures = 1,
        },
        [24] = {
            label = 'Đồng hồ cơ màu đồng quai đen',
            cType = 'props',
            drawble = 8,
            textures = 2,
        },
        [25] = {
            label = 'Đồng hồ ulm màu bạc',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },
        [26] = {
            label = 'Đồng hồ ulm màu đen',
            cType = 'props',
            drawble = 9,
            textures = 1,
        },
        [27] = {
            label = 'Đồng hồ ulm màu nâu',
            cType = 'props',
            drawble = 9,
            textures = 2,
        },
        [28] = {
            label = 'Đồng hồ rolec màu bạc',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },
        [29] = {
            label = 'Đồng hồ rolec màu đồng',
            cType = 'props',
            drawble = 10,
            textures = 1,
        },
        [30] = {
            label = 'Đồng hồ rolec màu đen',
            cType = 'props',
            drawble = 10,
            textures = 2,
        },
        [31] = {
            label = 'Đồng hồ cơ mạ đồng',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },
        [32] = {
            label = 'Đồng hồ cơ mạ bạc',
            cType = 'props',
            drawble = 11,
            textures = 1,
        },
        [33] = {
            label = 'Đồng hồ cơ mạ bạch kim',
            cType = 'props',
            drawble = 11,
            textures = 2,
        },
        [34] = {
            label = 'Đồng hồ ngũ giác mặt đen',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },
        [35] = {
            label = 'Đồng hồ ngũ giác mặt trắng',
            cType = 'props',
            drawble = 12,
            textures = 1,
        },
        [36] = {
            label = 'Đồng hồ ngũ giác điện tử',
            cType = 'props',
            drawble = 12,
            textures = 2,
        },
        [37] = {
            label = 'Đồng hồ ngũ giác điện tử quai đen',
            cType = 'props',
            drawble = 13,
            textures = 0,
        },
        [38] = {
            label = 'Đồng hồ ngũ giác điện tử quai xanh',
            cType = 'props',
            drawble = 13,
            textures = 1,
        },
        [39] = {
            label = 'Đồng hồ ngũ giác điện tử quai tím than',
            cType = 'props',
            drawble = 13,
            textures = 2,
        },
        [40] = {
            label = 'Đồng hồ gsoc màu bạc',
            cType = 'props',
            drawble = 14,
            textures = 0,
        }, 
        [41] = {
            label = 'Đồng hồ gsoc màu đồng',
            cType = 'props',
            drawble = 14,
            textures = 1,
        },
        [42] = {
            label = 'Đồng hồ gsoc màu bạch kim',
            cType = 'props',
            drawble = 14,
            textures = 2,
        },
        [43] = {
            label = 'Đồng hồ vesis verseca quai nâu',
            cType = 'props',
            drawble = 15,
            textures = 0,
        },
        [44] = {
            label = 'Đồng hồ vesis verseca quai đen',
            cType = 'props',
            drawble = 15,
            textures = 1,
        },
        [45] = {
            label = 'Đồng hồ vesis verseca quai vân',
            cType = 'props',
            drawble = 15,
            textures = 2,
        },
        [46] = {
            label = 'Đồng hồ timberlon màu vàng',
            cType = 'props',
            drawble = 16,
            textures = 0,
        },
        [47] = {
            label = 'Đồng hồ timberlon màu bạc',
            cType = 'props',
            drawble = 16,
            textures = 1,
        },
        [48] = {
            label = 'Đồng hồ timberlon màu xám',
            cType = 'props',
            drawble = 16,
            textures = 2,
        },
        [49] = {
            label = 'Đồng hồ lục giác màu nâu',
            cType = 'props',
            drawble = 17,
            textures = 0,
        },
        [50] = {
            label = 'Đồng hồ lục giác màu bạc quai nâu',
            cType = 'props',
            drawble = 17,
            textures = 1,
        },
        [51] = {
            label = 'Đồng hồ lục giác màu bạc quai đen',
            cType = 'props',
            drawble = 17,
            textures = 2,
        },
        [52] = {
            label = 'Đồng hồ nhựa màu đen',
            cType = 'props',
            drawble = 18,
            textures = 0,
        },
        [53] = {
            label = 'Đồng hồ nhựa màu bạc',
            cType = 'props',
            drawble = 18,
            textures = 1,
        },
        [54] = {
            label = 'Đồng hồ nhựa quai đen',
            cType = 'props',
            drawble = 18,
            textures = 2,
        },
        [55] = {
            label = 'Đồng hồ fessile twest màu bạc',
            cType = 'props',
            drawble = 19,
            textures = 0,
        },
        [56] = {
            label = 'Đồng hồ fessile twest màu đồng',
            cType = 'props',
            drawble = 19,
            textures = 1,
        },
        [57] = {
            label = 'Đồng hồ fessile twest màu đen',
            cType = 'props',
            drawble = 19,
            textures = 2,
        },
        [58] = {
            label = 'Đồng hồ gsoc màu đen',
            cType = 'props',
            drawble = 20,
            textures = 0,
        },
        [59] = {
            label = 'Đồng hồ gsoc màu đỏ',
            cType = 'props',
            drawble = 20,
            textures = 1,
        },
        [60] = {
            label = 'Đồng hồ gsoc màu vàng',
            cType = 'props',
            drawble = 20,
            textures = 2,
        },
        [61] = {
            label = 'Đồng hồ ngũ giác quai nâu',
            cType = 'props',
            drawble = 21,
            textures = 0,
        },
        [62] = {
            label = 'Đồng hồ ngũ giác quai xanh',
            cType = 'props',
            drawble = 21,
            textures = 1,
        },
        [63] = {
            label = 'Đồng hồ ngũ giác mặt xanh',
            cType = 'props',
            drawble = 21,
            textures = 2,
        },
        [64] = {
            label = 'Vòng tay xích bạc size m',
            cType = 'props',
            drawble = 22,
            textures = 0,
        },
        [65] = {
            label = 'Vòng tay xích bạc size l',
            cType = 'props',
            drawble = 23,
            textures = 0,
        },
        [66] = {
            label = 'Vòng tay bạc',
            cType = 'props',
            drawble = 24,
            textures = 0,
        },
        [67] = {
            label = 'Vòng tay bạc đầu lâu',
            cType = 'props',
            drawble = 25,
            textures = 0,
        },
        [68] = {
            label = 'Lắc tay bạc',
            cType = 'props',
            drawble = 26,
            textures = 0,
        },
        [69] = {
            label = 'Vòng tay trang trí đầu lâu',
            cType = 'props',
            drawble = 27,
            textures = 0,
        },
        [70] = {
            label = 'Lắc tay đính gai',
            cType = 'props',
            drawble = 28,
            textures = 0,
        },
        [71] = {
            label = 'Khăn vải quấn tay màu đen',
            cType = 'props',
            drawble = 29,
            textures = 0,
        },
        [72] = {
            label = 'Khăn vải quấn tay màu nâu đất',
            cType = 'props',
            drawble = 29,
            textures = 1,
        },
        [73] = {
            label = 'Khăn vải quấn tay màu vàng nhạt',
            cType = 'props',
            drawble = 29,
            textures = 2,
        },
        [74] = {
            label = 'Khăn vải quấn tay màu đồng đỏ',
            cType = 'props',
            drawble = 29,
            textures = 3,
        },
        [75] = {
            label = 'Đồng hồ cavale vàng',
            cType = 'props',
            drawble = 30,
            textures = 0,
        },
        [76] = {
            label = 'Đồng hồ cavale bạc',
            cType = 'props',
            drawble = 30,
            textures = 1,
        },
        [77] = {
            label = 'Đồng hồ cavale màu đen',
            cType = 'props',
            drawble = 30,
            textures = 2,
        },
        [78] = {
            label = 'Đồng hồ màu bạc sọc đen',
            cType = 'props',
            drawble = 30,
            textures = 3,
        },
        [79] = {
            label = 'Đồng hồ cavale màu vàng đen',
            cType = 'props',
            drawble = 30,
            textures = 4,
        },
        [80] = {
            label = 'Đồng hồ cavalea quai xám sọc đen',
            cType = 'props',
            drawble = 30,
            textures = 5,
        },
        [81] = {
            label = 'Đồng hồ med vàng',
            cType = 'props',
            drawble = 31,
            textures = 0,
        },
        [82] = {
            label = 'Đồng hồ med bạc',
            cType = 'props',
            drawble = 31,
            textures = 1,
        },
        [83] = {
            label = 'Đồng hồ med màu đen',
            cType = 'props',
            drawble = 31,
            textures = 2,
        },
        [84] = {
            label = 'Đồng hồ med màu trắng',
            cType = 'props',
            drawble = 31,
            textures = 3,
        },
        [85] = {
            label = 'Đồng hồ med màu vàng',
            cType = 'props',
            drawble = 31,
            textures = 4,
        },
        [86] = {
            label = 'Đồng hồ med màu đen mặt đỏ',
            cType = 'props',
            drawble = 31,
            textures = 5,
        },
        [87] = {
            label = 'Đồng hồ fiju vàng',
            cType = 'props',
            drawble = 32,
            textures = 0,
        },
        [88] = {
            label = 'Đồng hồ fiju bạc quai nâu',
            cType = 'props',
            drawble = 32,
            textures = 1,
        },
        [89] = {
            label = 'Đồng hồ fiju bạc quai đen',
            cType = 'props',
            drawble = 32,
            textures = 2,
        },
        [90] = {
            label = 'Đồng hồ fiju mạ bạc quai nâu',
            cType = 'props',
            drawble = 32,
            textures = 3,
        },
        [91] = {
            label = 'Đồng hồ fiju mạ bạc quai đỏ',
            cType = 'props',
            drawble = 32,
            textures = 4,
        },
        [92] = {
            label = 'Đồng hồ fiju mạ bạc quai đen',
            cType = 'props',
            drawble = 32,
            textures = 5,
        },
        [93] = {
            label = 'Đồng hồ fiju mạ vàng mặt đỏ đỏ',
            cType = 'props',
            drawble = 32,
            textures = 6,
        },
        [94] = {
            label = 'Đồng hồ fiju mạ vàng mặt đen',
            cType = 'props',
            drawble = 32,
            textures = 7,
        },
        [95] = {
            label = 'Đồng hồ fiju mạ vàng mặt xanh dương',
            cType = 'props',
            drawble = 32,
            textures = 8,
        },
        [96] = {
            label = 'Đồng hồ fiju mạ vàng mặt đen',
            cType = 'props',
            drawble = 32,
            textures = 9,
        },
        [97] = {
            label = 'Đồng hồ penari vàng',
            cType = 'props',
            drawble = 33,
            textures = 0,
        },
        [98] = {
            label = 'Đồng hồ penari bạc',
            cType = 'props',
            drawble = 33,
            textures = 1,
        },
        [99] = {
            label = 'Đồng hồ penari xanh dương',
            cType = 'props',
            drawble = 33,
            textures = 2,
        },
        [100] = {
            label = 'Đồng hồ penari xanh dương mặt vàng',
            cType = 'props',
            drawble = 33,
            textures = 3,
        },
        [101] = {
            label = 'Đồng hồ penari mạ vàng quai sọc nâu',
            cType = 'props',
            drawble = 33,
            textures = 4,
        },
        [102] = {
            label = 'Đồng hồ penari mạ vàng quai nâu',
            cType = 'props',
            drawble = 33,
            textures = 5,
        },
        [103] = {
            label = 'Đồng hồ ventage vàng',
            cType = 'props',
            drawble = 34,
            textures = 0,
        },
        [104] = {
            label = 'Đồng hồ ventage bạc',
            cType = 'props',
            drawble = 34,
            textures = 1,
        },
        [105] = {
            label = 'Đồng hồ ventage xanh dương',
            cType = 'props',
            drawble = 34,
            textures = 2,
        },
        [106] = {
            label = 'Đồng hồ ventage sọc trắng',
            cType = 'props',
            drawble = 34,
            textures = 3,
        },
        [107] = {
            label = 'Đồng hồ ventage quai mạ vàng',
            cType = 'props',
            drawble = 34,
            textures = 4,
        },
        [108] = {
            label = 'Đồng hồ ventage vàng quai đen',
            cType = 'props',
            drawble = 34,
            textures = 5,
        },
        [109] = {
            label = 'Đồng hồ chonr trắng',
            cType = 'props',
            drawble = 35,
            textures = 0,
        },
        [110] = {
            label = 'Đồng hồ chonr vàng',
            cType = 'props',
            drawble = 35,
            textures = 1,
        },
        [111] = {
            label = 'Đồng hồ chonr xanh dương',
            cType = 'props',
            drawble = 35,
            textures = 2,
        },
        [112] = {
            label = 'Đồng hồ chonr vàng quai sọc trắng',
            cType = 'props',
            drawble = 35,
            textures = 3,
        },
        [113] = {
            label = 'Đồng hồ chonr quai vàng',
            cType = 'props',
            drawble = 35,
            textures = 4,
        },
        [114] = {
            label = 'Đồng hồ The Cushion quai đỏ',
            cType = 'props',
            drawble = 35,
            textures = 5,
        },
        [115] = {
            label = 'Đồng hồ the sushon vàng',
            cType = 'props',
            drawble = 36,
            textures = 0,
        },
        [116] = {
            label = 'Đồng hồ the sushon bạc',
            cType = 'props',
            drawble = 36,
            textures = 1,
        },
        [117] = {
            label = 'Đồng hồ the sushon xanh dương',
            cType = 'props',
            drawble = 36,
            textures = 2,
        },
        [118] = {
            label = 'Đồng hồ the sushon vàng quai nâu',
            cType = 'props',
            drawble = 36,
            textures = 3,
        },
        [119] = {
            label = 'Đồng hồ the sushon bạc quai sọc vàng',
            cType = 'props',
            drawble = 36,
            textures = 4,
        },
        [120] = {
            label = 'Đồng hồ the sushon xanh dương quai đen',
            cType = 'props',
            drawble = 36,
            textures = 5,
        },
        [121] = {
            label = 'Đồng hồ the dupud qurt bạc',
            cType = 'props',
            drawble = 37,
            textures = 0,
        },
        [122] = {
            label = 'Đồng hồ the dupud qurt vàng',
            cType = 'props',
            drawble = 37,
            textures = 1,
        },
        [123] = {
            label = 'Đồng hồ the dupud qurt xanh dương',
            cType = 'props',
            drawble = 37,
            textures = 2,
        },
        [124] = {
            label = 'Đồng hồ the dupud qurt xanh dương mặt trắng',
            cType = 'props',
            drawble = 37,
            textures = 3,
        },
        [125] = {
            label = 'Đồng hồ the dupud qurt bạc quai nâu',
            cType = 'props',
            drawble = 37,
            textures = 4,
        },
        [126] = {
            label = 'Đồng hồ the dupud qurt xanh dương quai nâu',
            cType = 'props',
            drawble = 37,
            textures = 5,
        },
        [127] = {
            label = 'Lắc bạc sass',
            cType = 'props',
            drawble = 38,
            textures = 0,
        },
        [128] = {
            label = 'Lắc vàng sass',
            cType = 'props',
            drawble = 38,
            textures = 1,
        },
        [129] = {
            label = 'Lắc đen sass',
            cType = 'props',
            drawble = 38,
            textures = 2,
        },
        [130] = {
            label = 'Lắc bạc sass v2',
            cType = 'props',
            drawble = 39,
            textures = 0,
        },
        [131] = {
            label = 'Lắc vàng sass v2',
            cType = 'props',
            drawble = 39,
            textures = 1,
        },
        [132] = {
            label = 'Lắc đen sass v2',
            cType = 'props',
            drawble = 39,
            textures = 2,
        },
        [133] = {
            label = 'Vòng nhựa tím',
            cType = 'props',
            drawble = 40,
            textures = 0,
        },
        [134] = {
            label = 'Vòng nhựa đỏ',
            cType = 'props',
            drawble = 40,
            textures = 1,
        },
        [135] = {
            label = 'Vòng nhựa hồng',
            cType = 'props',
            drawble = 40,
            textures = 2,
        },
        [136] = {
            label = 'Vòng nhựa vàng',
            cType = 'props',
            drawble = 40,
            textures = 3,
        },
        [137] = {
            label = 'Vòng nhựa cam',
            cType = 'props',
            drawble = 40,
            textures = 4,
        },
        [138] = {
            label = 'Vòng nhựa xanh lá',
            cType = 'props',
            drawble = 40,
            textures = 5,
        },
        [139] = {
            label = 'Vòng nhựa tím đỏ',
            cType = 'props',
            drawble = 40,
            textures = 6,
        },
        [140] = {
            label = 'Vòng nhựa cam vàng',
            cType = 'props',
            drawble = 40,
            textures = 7,
        },
        [141] = {
            label = 'Vòng nhựa tím xanh lá',
            cType = 'props',
            drawble = 40,
            textures = 8,
        },
        [142] = {
            label = 'Vòng nhựa đa sắc',
            cType = 'props',
            drawble = 40,
            textures = 9,
        },
        [143] = {
            label = 'Vòng nhựa màu nóng',
            cType = 'props',
            drawble = 40,
            textures = 10,
        },
        [144] = {
            label = 'Vòng nhựa đa sắc 2',
            cType = 'props',
            drawble = 40,
            textures = 11,
        },
        [145] = {
            label = 'Vòng vàng đính ngọc',
            cType = 'props',
            drawble = 41,
            textures = 0,
        },
        [146] = {
            label = 'Vòng bạc đính ngọc',
            cType = 'props',
            drawble = 41,
            textures = 1,
        },
        [147] = {
            label = 'Vòng màu hồng đính ngọc',
            cType = 'props',
            drawble = 41,
            textures = 2,
        },
        [148] = {
            label = 'lắc tay vàng đính kim cương',
            cType = 'props',
            drawble = 42,
            textures = 0,
        },
        [149] = {
            label = 'lắc tay bạc đính kim cương',
            cType = 'props',
            drawble = 42,
            textures = 1,
        },
        [150] = {
            label = 'lắc tay màu hồng đính kim cương',
            cType = 'props',
            drawble = 42,
            textures = 2,
        },
        [151] = {
            label = 'vòng vàng nhỏ',
            cType = 'props',
            drawble = 43,
            textures = 0,
        },
        [152] = {
            label = 'vòng bạc nhỏ',
            cType = 'props',
            drawble = 43,
            textures = 1,
        },
        [153] = {
            label = 'vòng màu hồng nhỏ',
            cType = 'props',
            drawble = 43,
            textures = 2,
        },
        [154] = {
            label = 'vòng vàng hình ổ khóa',
            cType = 'props',
            drawble = 44,
            textures = 0,
        },
        [155] = {
            label = 'vòng bạc hình ổ khóa',
            cType = 'props',
            drawble = 44,
            textures = 1,
        },
        [156] = {
            label = 'vòng màu hồng hình ổ khóa',
            cType = 'props',
            drawble = 44,
            textures = 2,
        },                
    },

    female = {
        [1] = {
            label = 'Đồng hồ cytyzen bajc',
            cType = 'props',
            drawble = 0,
            textures = 4,
        },
        [2] = {
            label = 'Đồng hồ cytyzen 1',
            cType = 'props',
            drawble = 2,
            textures = 0,
        },
        [3] = {
            label = 'Đồng hồ cytyzen 2',
            cType = 'props',
            drawble = 2,
            textures = 1,
        },
        [4] = {
            label = 'Đồng hồ cytyzen 3',
            cType = 'props',
            drawble = 2,
            textures = 2,
        },
        [5] = {
            label = 'Đồng hồ egata 1',
            cType = 'props',
            drawble = 3,
            textures = 0,
        },
        [6] = {
            label = 'Đồng hồ egata 2',
            cType = 'props',
            drawble = 3,
            textures = 1,
        },
        [7] = {
            label = 'Đồng hồ egata 3',
            cType = 'props',
            drawble = 3,
            textures = 2,
        },
        [8] = {
            label = 'Đồng hồ seko 1',
            cType = 'props',
            drawble = 4,
            textures = 0,
        },
        [9] = {
            label = 'Đồng hồ seko 2',
            cType = 'props',
            drawble = 4,
            textures = 1,
        },
        [10] = {
            label = 'Đồng hồ seko 3',
            cType = 'props',
            drawble = 4,
            textures = 2,
        },
        [11] = {
            label = 'Đồng hồ lục giác 1',
            cType = 'props',
            drawble = 5,
            textures = 0,
        },
        [12] = {
            label = 'Đồng hồ lục giác 2',
            cType = 'props',
            drawble = 5,
            textures = 1,
        },
        [13] = {
            label = 'Đồng hồ lục giác 3',
            cType = 'props',
            drawble = 5,
            textures = 2,
        },
        [14] = {
            label = 'Đồng hồ điện tử lục giác 1',
            cType = 'props',
            drawble = 6,
            textures = 0,
        },
        [15] = {
            label = 'Đồng hồ điện tử lục giác 2',
            cType = 'props',
            drawble = 6,
            textures = 1,
        },
        [16] = {
            label = 'Đồng hồ điện tử lục giác 3',
            cType = 'props',
            drawble = 6,
            textures = 2,
        },
        [17] = {
            label = 'Đồng hồ ramon 1',
            cType = 'props',
            drawble = 7,
            textures = 0,
        },
        [18] = {
            label = 'Đồng hồ ramon 2',
            cType = 'props',
            drawble = 7,
            textures = 1,
        },
        [19] = {
            label = 'Đồng hồ ramon 3',
            cType = 'props',
            drawble = 7,
            textures = 2,
        },
        [20] = {
            label = 'Đồng hồ vuông 1',
            cType = 'props',
            drawble = 8,
            textures = 0,
        },
        [21] = {
            label = 'Đồng hồ vuông 2',
            cType = 'props',
            drawble = 8,
            textures = 1,
        },
        [22] = {
            label = 'Đồng hồ vuông 3',
            cType = 'props',
            drawble = 8,
            textures = 2,
        },
        [23] = {
            label = 'Đồng hồ lop 1',
            cType = 'props',
            drawble = 9,
            textures = 0,
        },
        [24] = {
            label = 'Đồng hồ lop 2',
            cType = 'props',
            drawble = 9,
            textures = 1,
        },
        [25] = {
            label = 'Đồng hồ lop 3',
            cType = 'props',
            drawble = 9,
            textures = 2,
        },
        [26] = {
            label = 'Đồng hồ lục giác đa sắc 1',
            cType = 'props',
            drawble = 10,
            textures = 0,
        },
        [27] = {
            label = 'Đồng hồ lục giác đa sắc 2',
            cType = 'props',
            drawble = 10,
            textures = 1,
        },
        [28] = {
            label = 'Đồng hồ lục giác đa sắc 3',
            cType = 'props',
            drawble = 10,
            textures = 2,
        },
        [29] = {
            label = 'Vòng tay bạc nhỏ',
            cType = 'props',
            drawble = 11,
            textures = 0,
        },
        [30] = {
            label = 'Vòng tay bạc lớn',
            cType = 'props',
            drawble = 12,
            textures = 0,
        },
        [31] = {
            label = 'Lắc tay bạc nhỏ',
            cType = 'props',
            drawble = 13,
            textures = 0,
        },
        [32] = {
            label = 'Lắc tay đầu lâu',
            cType = 'props',
            drawble = 14,
            textures = 0,
        },
        [33] = {
            label = 'Lắc tay bạc lớn',
            cType = 'props',
            drawble = 15,
            textures = 0,
        },
        [34] = {
            label = 'Vòng tay lớn',
            cType = 'props',
            drawble = 16,
            textures = 0,
        },
        [35] = {
            label = 'Vòng tay gắn đinh',
            cType = 'props',
            drawble = 17,
            textures = 0,
        },
        [36] = {
            label = 'Đai đeo tay 1',
            cType = 'props',
            drawble = 18,
            textures = 0,
        },
        [37] = {
            label = 'Đai đeo tay 2',
            cType = 'props',
            drawble = 18,
            textures = 1,
        },
        [38] = {
            label = 'Đai đeo tay 3',
            cType = 'props',
            drawble = 18,
            textures = 2,
        },
        [39] = {
            label = 'Đai đeo tay 4',
            cType = 'props',
            drawble = 18,
            textures = 3,
        },
        [40] = {
            label = 'Đồng hồ elgan 1',
            cType = 'props',
            drawble = 19,
            textures = 0,
        }, 
        [41] = {
            label = 'Đồng hồ elgan 2',
            cType = 'props',
            drawble = 19,
            textures = 1,
        },
        [42] = {
            label = 'Đồng hồ elgan 3',
            cType = 'props',
            drawble = 19,
            textures = 2,
        },
        [43] = {
            label = 'Đồng hồ elgan 4',
            cType = 'props',
            drawble = 19,
            textures = 3,
        },
        [44] = {
            label = 'Đồng hồ elgan 5',
            cType = 'props',
            drawble = 19,
            textures = 4,
        },
        [45] = {
            label = 'Đồng hồ elgan 6',
            cType = 'props',
            drawble = 19,
            textures = 5,
        },
        [46] = {
            label = 'Đồng hồ siko 1',
            cType = 'props',
            drawble = 20,
            textures = 0,
        },
        [47] = {
            label = 'Đồng hồ siko 2',
            cType = 'props',
            drawble = 20,
            textures = 1,
        },
        [48] = {
            label = 'Đồng hồ siko 3',
            cType = 'props',
            drawble = 20,
            textures = 2,
        },
        [49] = {
            label = 'Đồng hồ siko 4',
            cType = 'props',
            drawble = 20,
            textures = 3,
        },
        [50] = {
            label = 'Đồng hồ siko 5',
            cType = 'props',
            drawble = 20,
            textures = 4,
        },
        [51] = {
            label = 'Đồng hồ siko 6',
            cType = 'props',
            drawble = 20,
            textures = 5,
        },
        [52] = {
            label = 'Đồng hồ fiju 1',
            cType = 'props',
            drawble = 21,
            textures = 0,
        },
        [53] = {
            label = 'Đồng hồ fiju 2',
            cType = 'props',
            drawble = 21,
            textures = 1,
        },
        [54] = {
            label = 'Đồng hồ fiju 3',
            cType = 'props',
            drawble = 21,
            textures = 2,
        },
        [55] = {
            label = 'Đồng hồ fiju 4',
            cType = 'props',
            drawble = 21,
            textures = 3,
        },
        [56] = {
            label = 'Đồng hồ fiju 5',
            cType = 'props',
            drawble = 21,
            textures = 4,
        },
        [57] = {
            label = 'Đồng hồ fiju 6',
            cType = 'props',
            drawble = 21,
            textures = 5,
        },
        [58] = {
            label = 'Đồng hồ fiju 7',
            cType = 'props',
            drawble = 21,
            textures = 6,
        },
        [59] = {
            label = 'Đồng hồ fiju 8',
            cType = 'props',
            drawble = 21,
            textures = 7,
        },
        [60] = {
            label = 'Đồng hồ fiju 9',
            cType = 'props',
            drawble = 21,
            textures = 8,
        },
        [61] = {
            label = 'Đồng hồ fiju 10',
            cType = 'props',
            drawble = 21,
            textures = 9,
        },
        [62] = {
            label = 'Đồng hồ jeo & oc 1',
            cType = 'props',
            drawble = 22,
            textures = 0,
        },
        [63] = {
            label = 'Đồng hồ jeo & oc 2',
            cType = 'props',
            drawble = 22,
            textures = 1,
        },
        [64] = {
            label = 'Đồng hồ jeo & oc 3',
            cType = 'props',
            drawble = 22,
            textures = 2,
        },
        [65] = {
            label = 'Đồng hồ jeo & oc 4',
            cType = 'props',
            drawble = 22,
            textures = 3,
        },
        [66] = {
            label = 'Đồng hồ jeo & oc 5',
            cType = 'props',
            drawble = 22,
            textures = 4,
        },
        [67] = {
            label = 'Đồng hồ jeo & oc 6',
            cType = 'props',
            drawble = 22,
            textures = 5,
        },
        [68] = {
            label = 'Đồng hồ givencha 1',
            cType = 'props',
            drawble = 23,
            textures = 0,
        },
        [69] = {
            label = 'Đồng hồ givencha 2',
            cType = 'props',
            drawble = 23,
            textures = 1,
        },
        [70] = {
            label = 'Đồng hồ givencha 3',
            cType = 'props',
            drawble = 23,
            textures = 2,
        },
        [71] = {
            label = 'Đồng hồ givencha 4',
            cType = 'props',
            drawble = 23,
            textures = 3,
        },
        [72] = {
            label = 'Đồng hồ givencha 5',
            cType = 'props',
            drawble = 23,
            textures = 4,
        },
        [73] = {
            label = 'Đồng hồ givencha 6',
            cType = 'props',
            drawble = 23,
            textures = 5,
        },
        [74] = {
            label = 'Đồng hồ hibrit 1',
            cType = 'props',
            drawble = 24,
            textures = 0,
        },
        [75] = {
            label = 'Đồng hồ hibrit 2',
            cType = 'props',
            drawble = 24,
            textures = 1,
        },
        [76] = {
            label = 'Đồng hồ hibrit 3',
            cType = 'props',
            drawble = 24,
            textures = 2,
        },
        [77] = {
            label = 'Đồng hồ hibrit 4',
            cType = 'props',
            drawble = 24,
            textures = 3,
        },
        [78] = {
            label = 'Đồng hồ hibrit 5',
            cType = 'props',
            drawble = 24,
            textures = 4,
        },
        [79] = {
            label = 'Đồng hồ hibrit 6',
            cType = 'props',
            drawble = 24,
            textures = 5,
        },
        [80] = {
            label = 'Đồng hồ fenliy 1',
            cType = 'props',
            drawble = 25,
            textures = 5,
        },
        [81] = {
            label = 'Đồng hồ fenliy 2',
            cType = 'props',
            drawble = 25,
            textures = 1,
        },
        [82] = {
            label = 'Đồng hồ fenliy 3',
            cType = 'props',
            drawble = 25,
            textures = 2,
        },
        [83] = {
            label = 'Đồng hồ fenliy 4',
            cType = 'props',
            drawble = 25,
            textures = 3,
        },
        [84] = {
            label = 'Đồng hồ fenliy 5',
            cType = 'props',
            drawble = 25,
            textures = 4,
        },
        [85] = {
            label = 'Đồng hồ fenliy 6',
            cType = 'props',
            drawble = 25,
            textures = 5,
        },
        [86] = {
            label = 'Đồng hồ fiju v2 1',
            cType = 'props',
            drawble = 26,
            textures = 0,
        },
        [87] = {
            label = 'Đồng hồ fiju v2 2',
            cType = 'props',
            drawble = 26,
            textures = 1,
        },
        [88] = {
            label = 'Đồng hồ fiju v2 3',
            cType = 'props',
            drawble = 26,
            textures = 2,
        },
        [89] = {
            label = 'Đồng hồ fiju v2 4',
            cType = 'props',
            drawble = 26,
            textures = 3,
        },
        [90] = {
            label = 'Đồng hồ fiju v2 5',
            cType = 'props',
            drawble = 26,
            textures = 4,
        },
        [91] = {
            label = 'Đồng hồ fiju v2 6',
            cType = 'props',
            drawble = 26,
            textures = 5,
        },
        [92] = {
            label = 'Đồng hồ sass 1',
            cType = 'props',
            drawble = 27,
            textures = 0,
        },
        [93] = {
            label = 'Đồng hồ sass 2',
            cType = 'props',
            drawble = 27,
            textures = 1,
        },
        [94] = {
            label = 'Đồng hồ sass 3',
            cType = 'props',
            drawble = 27,
            textures = 2,
        },
        [95] = {
            label = 'Đồng hồ sass tròn 1',
            cType = 'props',
            drawble = 28,
            textures = 0,
        },
        [96] = {
            label = 'Đồng hồ sass tròn 2',
            cType = 'props',
            drawble = 28,
            textures = 1,
        },
        [97] = {
            label = 'Đồng hồ sass tròn 3',
            cType = 'props',
            drawble = 28,
            textures = 2,
        },
        [98] = {
            label = 'Vòng nhựa 1',
            cType = 'props',
            drawble = 29,
            textures = 0,
        },
        [99] = {
            label = 'Vòng nhựa 2',
            cType = 'props',
            drawble = 29,
            textures = 1,
        },
        [100] = {
            label = 'Vòng nhựa 3',
            cType = 'props',
            drawble = 29,
            textures = 2,
        },
        [101] = {
            label = 'Vòng nhựa 4',
            cType = 'props',
            drawble = 29,
            textures = 3,
        },
        [102] = {
            label = 'Vòng nhựa 5',
            cType = 'props',
            drawble = 29,
            textures = 4,
        },
        [103] = {
            label = 'Vòng nhựa 6',
            cType = 'props',
            drawble = 29,
            textures = 5,
        },
        [104] = {
            label = 'Vòng nhựa 7',
            cType = 'props',
            drawble = 29,
            textures = 6,
        },
        [105] = {
            label = 'Vòng nhựa 8',
            cType = 'props',
            drawble = 29,
            textures = 7,
        },
        [106] = {
            label = 'Vòng nhựa 9',
            cType = 'props',
            drawble = 29,
            textures = 8,
        },
        [107] = {
            label = 'Vòng nhựa 10',
            cType = 'props',
            drawble = 29,
            textures = 9,
        },
        [108] = {
            label = 'Vòng nhựa 11',
            cType = 'props',
            drawble = 29,
            textures = 10,
        },
        [109] = {
            label = 'Vòng nhựa 12',
            cType = 'props',
            drawble = 29,
            textures = 11,
        },
        [110] = {
            label = 'Vòng ngọc trai 1',
            cType = 'props',
            drawble = 30,
            textures = 0,
        },
        [111] = {
            label = 'Vòng ngọc trai 2',
            cType = 'props',
            drawble = 30,
            textures = 1,
        },
        [112] = {
            label = 'Vòng ngọc trai 3',
            cType = 'props',
            drawble = 31,
            textures = 0,
        },
        [113] = {
            label = 'Lắc vàng',
            cType = 'props',
            drawble = 31,
            textures = 1,
        },
        [114] = {
            label = 'Lắc hồng',
            cType = 'props',
            drawble = 31,
            textures = 2,
        },
        [115] = {
            label = 'Vòng vàng',
            cType = 'props',
            drawble = 32,
            textures = 0,
        },
        [116] = {
            label = 'Vòng bạc',
            cType = 'props',
            drawble = 32,
            textures = 1,
        },
        [117] = {
            label = 'Vòng hồng',
            cType = 'props',
            drawble = 32,
            textures = 2,
        },
        [118] = {
            label = 'Lắc tay 1',
            cType = 'props',
            drawble = 33,
            textures = 0,
        },
        [119] = {
            label = 'Lắc tay 2',
            cType = 'props',
            drawble = 33,
            textures = 1,
        },
        [120] = {
            label = 'Lắc tay 3',
            cType = 'props',
            drawble = 33,
            textures = 2,
        },
        [121] = {
            label = 'Vòng tay ngọc trai 1',
            cType = 'props',
            drawble = 34,
            textures = 0,
        },
        [122] = {
            label = 'Vòng tay ngọc trai 2',
            cType = 'props',
            drawble = 34,
            textures = 1,
        },
        [123] = {
            label = 'Vòng tay ngọc trai 3',
            cType = 'props',
            drawble = 34,
            textures = 2,
        },
        [124] = {
            label = 'Vòng tay ngọc trai 4',
            cType = 'props',
            drawble = 34,
            textures = 3,
        },
        [125] = {
            label = 'Vòng tay ngọc trai 5',
            cType = 'props',
            drawble = 34,
            textures = 4,
        },
        [126] = {
            label = 'Vòng tay 1',
            cType = 'props',
            drawble = 35,
            textures = 0,
        },
        [127] = {
            label = 'Vòng tay 2',
            cType = 'props',
            drawble = 35,
            textures = 1,
        },
        [128] = {
            label = 'Vòng tay 3',
            cType = 'props',
            drawble = 35,
            textures = 2,
        },
        [129] = {
            label = 'Vòng tay 4',
            cType = 'props',
            drawble = 35,
            textures = 3,
        },
        [130] = {
            label = 'Vòng tay 5',
            cType = 'props',
            drawble = 35,
            textures = 4,
        },
    },
}